### ISSUE TITLE
What is the point?

### ISSUE THREAD

**Issue by iddm** [dtolnay/readonly#1]
I don't really understand what is the point in having struct members be read-only? If you always want something to have a constant value, what is the problem in Rust to defined a constant in a module scope?

If we make a struct like

```rust
mod m {
    #[readonly::make]
    pub struct String {
        pub max_length: i32,
    }

    impl String {
        fn new() -> String {
            String {
                max_length: 5
            }
        }
    }
}
```

what are the advantages over

```rust
mod m {
    pub const STRING_MAX_LENGTH: i32 = 5;
}
```

Or, another case, in case the `max_length` is mutable within `String`, what are the advantages of `readonly` over a getter?

```rust
mod m {
    pub struct String {
        pub max_length: i32,
    }

    impl String {
        fn max_length(&self) -> i32 {
            self.max_length
        }

        fn max_length_ref(&self) -> &i32 {
            &self.max_length
        }
    }
}
```

Or maybe there are other profits which the crate's README and documentation did not explain? Well, there are no explanation at all, about why is it better over something else. If there are really good use cases or major problems that it solves, I think it is worth to be in the language itself (or there is an RFC about it?).

Though I find this crate interesting, I am not sure where and when I need to use it. Adding some explanation and comparisons would be good I guess.

**Comment by dtolnay** [comment]
See an example of real usage in rust-quiz:

- https://github.com/dtolnay/rust-quiz/blob/a53ed678b3ca676e3dad4d53e8829482ce0ddcc0/src/broker.rs#L89-L94
- https://github.com/dtolnay/rust-quiz/blob/a53ed678b3ca676e3dad4d53e8829482ce0ddcc0/src/main.rs#L103

A module-level constant would not work because each instance carries a different index.

A getter would introduce parenthesis noise at the point of use.

A fully public writable field would allow caller to violate invariants of the module.

**Comment by iddm** [comment]
So this whole crate and all this work has been done specifically to avoid writing parentheses at the point of use?

**Comment by dtolnay** [comment]
Correct.

**Comment by iddm** [comment]
Looks a bit strange to me if this is the only use case. Nevertheless, it is an interesting crate, I did not even think that we could do something like that before. Thanks for the explanation.
